### ISSUE TITLE
Brier and ECE functions

### ISSUE THREAD

**Issue by RiqiangGao** [IntelLabs/AVUC#2]
Dear author, 

I found a few  codes lines commented, for example, 

#brier = np.mean(calib.brier_scores(target_labels, probs=pred_mean))
#ece = calib.expected_calibration_error_multiclass(pred_mean, target_labels)

which is also useful to me. Could I ask where can find the related functions? 

Thanks in advance.

**Comment by ranganathkrishnan** [comment]
Below are pointers to Brier and ECE functions from 'uncertainty-metrics' repo:
[https://github.com/google/uncertainty-metrics/blob/master/uncertainty_metrics/tensorflow/scoring_rules.py](url)
[https://github.com/google/uncertainty-metrics/blob/master/uncertainty_metrics/tensorflow/calibration.py](url)

**Comment by RiqiangGao** [comment]
Great! thank you a lot.

**Comment by ranganathkrishnan** [comment]
metrics_lib might also be helpful from [uq_benchmark](https://github.com/google-research/google-research/blob/master/uq_benchmark_2019/metrics_lib.py)

**Comment by RiqiangGao** [comment]
Very appreciate
