### ISSUE TITLE
Cannot find supplementary materials

### ISSUE THREAD

**Issue by jan-engelmann** [IntelLabs/AVUC#3]
In the [paper on arxiv](https://arxiv.org/abs/2012.07923) you refer to an appendix.
Unfortunately I have not been able to find it. Would you be so kind to share it?

**Comment by jan-engelmann** [comment]
I would for instance be interested how you calculate UCE exactly

**Comment by ranganathkrishnan** [comment]
@jan-engelmann the appendix material is provided in pages 13-26, with UCE described in section C.3 (page 16). 
Appendix available in this link as well: https://proceedings.neurips.cc/paper/2020/file/d3d9446802a44259755d38e6d163e820-Supplemental.pdf

**Comment by jan-engelmann** [comment]
Thank you so much @ranganathkrishnan 👍
